# This is a basic workflow that is manually triggered

name: Publish

# Controls when the action will run. Workflow runs when release is created
on:
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: test_and_publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        TAG_NAME:  ${{ github.event.release.tag_name }} 
      run: |
        echo Generating PyPi package for TAG_NAME=$TAG_NAME
        python -m pip install --upgrade pipenv
        pipenv install --dev
        ./test.sh
        ./createPackage.sh
        pipenv run twine upload dist/*
